### ISSUE TITLE
The value cannot be an empty string. (Parameter 'oldValue')

### ISSUE THREAD

**Issue by dluc** [freemindlabsinc/FreeMindLabs.KernelMemory.Elasticsearch#34]
Running KM functional tests with 0.9.5, looks like there's a couple of regressions:

![image](https://github.com/freemindlabsinc/FreeMindLabs.KernelMemory.Elasticsearch/assets/371009/252b71a8-8ed0-439d-9115-cdbe31c7caa0)

## ItHandlesMissingIndexesConsistently

```
System.ArgumentException
The value cannot be an empty string. (Parameter 'oldValue')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.String.Replace(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue, StringComparison comparisonType)
   at FreeMindLabs.KernelMemory.Elasticsearch.ElasticsearchMemory.<GetIndexesAsync>b__7_0(KeyValuePair`2 x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at FreeMindLabs.KernelMemory.Elasticsearch.ElasticsearchMemory.GetIndexesAsync(CancellationToken cancellationToken)
   at Microsoft.KernelMemory.MemoryServerless.ListIndexesAsync(CancellationToken cancellationToken) in service/Core/MemoryServerless.cs:line 143
```

## ItListsIndexes

```
System.ArgumentException
The value cannot be an empty string. (Parameter 'oldValue')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.String.Replace(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue, StringComparison comparisonType)
   at FreeMindLabs.KernelMemory.Elasticsearch.ElasticsearchMemory.<GetIndexesAsync>b__7_0(KeyValuePair`2 x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at FreeMindLabs.KernelMemory.Elasticsearch.ElasticsearchMemory.GetIndexesAsync(CancellationToken cancellationToken)
   at Microsoft.KernelMemory.MemoryServerless.ListIndexesAsync(CancellationToken cancellationToken) in service/Core/MemoryServerless.cs:line 143
```

## ES:
```
docker run -it --rm --name elasticsearch \
  -p 9200:9200 -p 9300:9300 \
  -e "discovery.type=single-node" elasticsearch:8.11.3
```

## Configuration:

```json
      "Elasticsearch": {
        "CertificateFingerPrint": "...",
        "Endpoint": "https://localhost:9200",
        "UserName": "elastic",
        "Password": "...",
        "IndexPrefix": "",
        "ShardCount": 1,
        "Replicas": 0
      },
```

**Comment by afederici75** [comment]
@dluc Sorry I disappeared, lots of stuff happening. I will address this shortly!
